apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-event-store
  labels:
    project: sob
    app: api-event-store
    layer: api
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: api-event-store
  template:
    metadata:
      labels:
        project: sob
        app: api-event-store
        layer: api
    spec:
      containers:
        - name: api-event-store
          image: postgres:13
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sob-secret
                  key: api-event-store-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sob-secret
                  key: api-event-store-password
          volumeMounts:
            - name: api-event-store-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "1m"
              memory: "128Mi"
      volumes:
        - name: api-event-store-storage
          persistentVolumeClaim:
            claimName: api-event-store-pvc
