apiVersion: v1
kind: Service
metadata:
  name: api-event-store-service
  labels:
    project: sob
    app: api-event-store-service
    layer: api
spec:
  ports:
    - port: 5432
  selector:
    app: api-event-store
  clusterIP: None
