extends: default

ignore: |
  api/bin
  api/dist
  api/vendor
  frontend/dist
  frontend/node_modules

rules:
  document-start: disable
  line-length: disable
  truthy: disable
  braces: { min-spaces-inside: 1, max-spaces-inside: 1, min-spaces-inside-empty: 0, max-spaces-inside-empty: 0 }
  comments: false
  comments-indentation: false
  indentation:
    spaces: 2
