version: '3.7'

services:
  markdown-linter:
    build:
      context: docker/markdown-linter
    volumes:
      - ./:/app
    working_dir: /app

  yaml-linter:
    build:
      context: docker/yaml-linter
    volumes:
      - ./:/app
    working_dir: /app

  commit-linter:
    build:
      context: docker/commit-linter
    volumes:
      - ./:/app
    working_dir: /app

  api-webserver:
    build:
      context: docker/api-webserver
    volumes:
      - ./api:/app
    working_dir: /app
    networks:
      default:
        aliases:
          - local.api.seaofbottles.aperturedevs.com
    depends_on:
      - api-database
      - broker

  api-cli:
    build:
      context: docker/api-cli
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - api-database
      - broker
      - mailer

  api-worker:
    build:
      context: docker/api-cli
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - api-database
      - broker
    restart: on-failure
    command: bin/console messenger:consume message_broker -vv

  api-database:
    image: postgres:13
    volumes:
      - api-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sob
      POSTGRES_PASSWORD: password

  frontend-webserver:
    image: node:lts
    expose:
      - 4200
    command: npx ng serve --host 0.0.0.0 --disable-host-check --poll=5000
    volumes:
      - ./frontend:/app
    working_dir: /app

  frontend-cli:
    build:
      context: docker/frontend-cli
    volumes:
      - ./frontend:/app
    working_dir: /app
    depends_on:
      - api-webserver

  broker:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "sob"
      RABBITMQ_DEFAULT_PASS: "password"
    hostname: broker
    volumes:
      - broker-data:/var/lib/rabbitmq

  mailer:
    image: maildev/maildev
    restart: on-failure
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS

volumes:
  api-database-data: ~
  broker-data: ~
