version: '3.7'

services:
  markdown-linter:
    build:
      context: docker/markdown-linter
    volumes:
      - ./:/app
    working_dir: /app

  yaml-linter:
    build:
      context: docker/yaml-linter
    volumes:
      - ./:/app
    working_dir: /app

  commit-linter:
    build:
      context: docker/commit-linter
    volumes:
      - ./:/app
    working_dir: /app

  api-webserver:
    build:
      context: docker/api-webserver
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - api-database
      - message-broker
    environment:
      CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$$

  api-cli:
    build:
      context: docker/api-cli
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - api-database
      - message-broker
      - mailer
    environment:
      CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$$

  api-worker:
    build:
      context: docker/api-cli
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - api-database
      - message-broker
    restart: on-failure
    environment:
      CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$$
    command: bin/console messenger:consume message_broker -vv

  api-database:
    image: postgres:13
    volumes:
      - api-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sob
      POSTGRES_PASSWORD: password

  message-broker:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "sob"
      RABBITMQ_DEFAULT_PASS: "password"

  shell-linter:
    build:
      context: docker/shell-linter
    volumes:
      - ./:/app

  shell-runner:
    image: bash:5
    volumes:
      - ./:/app

  mailer:
    image: maildev/maildev
    restart: on-failure
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS

volumes:
  api-database-data: ~
