version: '3'

tasks:

  ########
  # MAIN #
  ########

  check:
    desc: Check and fix sources
    cmds:
      - task: lint
      - task: global-commit-linter-check
      - task: global-yaml-linter-check
      - task: global-markdown-linter-check

  lint:
    desc: Lint sources
    cmds:
      - task: global-markdown-linter

  ##########
  # GLOBAL #
  ##########

  global-yaml-linter-check:
    desc: Check linter rules to YAML files
    cmds:
      - docker-compose run --rm yaml-linter yamllint -c .yamllint.yaml .

  global-markdown-linter:
    desc: Apply linter rules to markdown files
    cmds:
      - docker-compose run --rm markdown-linter markdownlint '**/*.md' -c .markdownlint.yaml --fix

  global-markdown-linter-check:
    desc: Check linter rules to markdown files
    cmds:
      - docker-compose run --rm markdown-linter markdownlint '**/*.md' -c .markdownlint.yaml

  global-commit-linter-check:
    desc: Checks if commit messages meet the conventional commit format
    cmds:
      - docker-compose run --rm commit-linter commitlint --from $(git rev-list --max-parents=0 HEAD)
