framework:
  messenger:
    default_bus: command.bus
    failure_transport: failed
    buses:
      command.bus: ~
      query.bus: ~
      event.bus: ~
    transports:
      message_broker:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          delay: 1000
          multiplier: 2
          max_delay: 0
      failed: 'doctrine://event_store?queue_name=failed'
