apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
  labels:
    project: sob
    app: message-broker
    layer: infra
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        project: sob
        app: message-broker
        layer: infra
    spec:
      containers:
        - name: message-broker
          image: rabbitmq:3-management
          imagePullPolicy: Always
          ports:
            - containerPort: 15672
              name: http
            - containerPort: 5672
              name: amqp
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: sob-secret
                  key: message-broker-user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: sob-secret
                  key: message-broker-password
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "1m"
              memory: "256Mi"
