apiVersion: v1
kind: Service
metadata:
  name: broker-amqp-service
  labels:
    project: sob
    app: broker-amqp-service
    layer: infra
spec:
  ports:
    - port: 5672
  selector:
    app: broker
  clusterIP: None
