apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-pvc
  labels:
    project: sob
    layer: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
