apiVersion: v1
kind: Service
metadata:
  name: api-relational-database-service
  labels:
    project: sob
    app: api-relational-database-service
    layer: api
spec:
  ports:
    - port: 5432
  selector:
    app: api-relational-database
  clusterIP: None
