apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-relational-database-pvc
  labels:
    project: sob
    layer: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
