apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  labels:
    project: sob
    layer: frontend
data:
  nginx.conf: |
    server {
        listen 80;
        server_name seaofbottles.aperturedevs.com;
        root /app;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
