parameters:
  container.dumper.inline_factories: true
  container.dumper.inline_class_loader: true
  email.contact: 'seaofbottles@aperturedevs.com'
  frontend.url: '%env(FRONTEND_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      Doctrine\ORM\EntityManagerInterface $eventStoreEntityManager: '@doctrine.orm.event_store_entity_manager'
      Doctrine\ORM\EntityManagerInterface $relationalModelEntityManager: '@doctrine.orm.relational_model_entity_manager'
      string $contactEmail: '%email.contact%'

  App\:
    resource: '../src/'
    exclude:
      - ../src/Core/Component/*/Domain
      - ../src/Core/SharedKernel/Domain
      - ../src/Kernel.php
      - ../src/Infrastructure/Persistence/*/Migration

  _instanceof:
    App\Core\SharedKernel\Application\CommandHandlerInterface:
      public: true
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    App\Core\SharedKernel\Application\QueryHandlerInterface:
      public: true
      tags:
        - { name: messenger.message_handler, bus: query.bus }

    App\Core\SharedKernel\Application\EventHandlerInterface:
      public: true
      tags:
        - { name: messenger.message_handler, bus: event.bus }

  App\Infrastructure\Exception\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
