services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Framework\TestDecorator\LockableClock:
    decorates: App\Core\SharedKernel\Port\ClockInterface

  App\Tests\Framework\AggregatePersister:
    public: true
