apiVersion: v1
kind: Service
metadata:
  name: frontend-webserver-http-service
  labels:
    project: sob
    layer: frontend
spec:
  ports:
    - port: 80
  selector:
    app: frontend-webserver
  clusterIP: None
