apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  frontend_url: "https://dev.seaofbottles.aperturedevs.com"
  environment: "dev"
  cors: ^https?://dev\.seaofbottles\.aperturedevs\.com$
  nginx.conf: |
    server {
        listen 80;
        server_name dev.api.seaofbottles.aperturedevs.com;
        root /var/www/html/public;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            internal;
        }

        location ~ \.php$ {
            return 404;
        }
    }
  php.ini: |
    opcache.memory_consumption=128
    opcache.max_accelerated_files=20000
    opcache.validate_timestamps=0
    realpath_cache_size=4096K
    realpath_cache_ttl=600
