apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sob-dev
commonLabels:
  tier: dev
resources:
  - ../../base
  - dev-namespace.yaml
  - api-relational-database-migration-job.yaml
  - api-event-store-migration-job.yaml
  - mailer-deployment.yaml
  - mailer-smtp-service.yaml
  - mailer-http-service.yaml
patchesStrategicMerge:
  - api-configmap.yaml
