apiVersion: v1
kind: Service
metadata:
  name: mailer-smtp-service
  labels:
    project: sob
    app: mailer-smtp-service
    layer: infra
spec:
  ports:
    - port: 25
  selector:
    app: mailer
  clusterIP: None
