apiVersion: v1
kind: Service
metadata:
  name: mailer-http-service
  labels:
    project: sob
    app: mailer-http-service
    layer: infra
spec:
  ports:
    - port: 80
  selector:
    app: mailer
  clusterIP: None
