name: Security Audit

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  frontend-audit:
    name: Frontend Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add Task runner
        run: |
          curl -sL https://taskfile.dev/install.sh | sh && echo "./bin" >> $GITHUB_PATH
      - name: Frontend Dependencies Audit
        run: |
          task frontend-dependencies-audit --summary
          task frontend-dependencies-audit
  api-audit:
    name: API Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add Task runner
        run: |
          curl -sL https://taskfile.dev/install.sh | sh && echo "./bin" >> $GITHUB_PATH
      - name: API Dependencies Security Check
        run: |
          task api-dependencies-security-check --summary
          task api-dependencies-security-check
